app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField,FileAllowed

from app.users.model import User


class LoginForm(FlaskForm):
    # email = StringField('Email',validators=[DataRequired(),Email()])
    email = StringField('Email')
    password = PasswordField('Password',validators=[DataRequired()])
    submit = SubmitField('Log In')

class RegistrationForm(FlaskForm):
    name = StringField('Full Name',validators=[DataRequired()])
    phone = StringField('Phone',validators=[])
    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password',validators=[DataRequired(),EqualTo('pass_confirm',message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm Password',validators=[DataRequired()])
    submit = SubmitField('Register!')
    
    def check_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

app/__init__.py
import os
from flask import Flask, render_template, jsonify, request
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_restful import Api
from flask_jwt_extended import JWTManager
from flask_cors import CORS
from datetime import datetime, timedelta

import subprocess

login_manager = LoginManager()

app = Flask(__name__)

app.config['SECRET_KEY'] = 'plkf124Fas4'
app.config['JWT_SECRET_KEY'] = 'plkf124Fas4'
app.config['JWT_BLACKLIST_ENABLED'] = True
# app.config['JWT_ACCESS_TOKEN_EXPIRES'] = timedelta(days=1)
# basedir = os.path.abspath(os.path.dirname(__file__))
# app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://admin:Pswd123$@db1.cdlikiuniwlk.sa-east-1.rds.amazonaws.com/db'
# app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://db:mysecret@db1.cdlikiuniwlk.sa-east-1.rds.amazonaws.com/db'

# app.config.update(
#     SESSION_COOKIE_SECURE=True,
#     SESSION_COOKIE_HTTPONLY=True,
#     SESSION_COOKIE_SAMESITE='Lax',
# )


app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

@app.before_first_request
def dbCreate():
    db.create_all()

api = Api(app)
jwt = JWTManager(app)

db = SQLAlchemy(app)
Migrate(app,db)

CORS(app)

########################################
# LOGIN CONFIGS

login_manager.init_app(app)
login_manager.login_view = "users.login"

# @app.after_request
# def after_request(response):
# #   response.headers.add('Access-Control-Allow-Headers', 'Content-Type,Authorization')
# #   response.headers.add('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE')
# #   response.headers.add('X-Frame-Options', 'SAMEORIGIN')
# #   response.headers.add('X-Content-Type-Options', 'nosniff')
# #   response.headers.add('X-XSS-Protection', '1; mode=block')
# #   response.headers['X-XSS-Protection'] = '1; mode=block'

#   response.headers.add('Content-Security-Policy', "script-src 'self' code.jquery.com cdnjs.cloudflare.com maxcdn.bootstrapcdn.com")
#   return response

@app.route('/')
def index():
    return render_template('home.html')

@app.route("/subscribe", methods=["GET","POST"])
def get_email1():
    temp = ""
    if request.method == "GET":

        return render_template("subscribe.html",data=temp)

    if request.method == "POST":
        if request.form.get("email"):
            emailurl = request.form.get("email")
            print(emailurl)
            email =  request.form.get("email") + " has succesfully subscribed to APPsecengineer"
            process = subprocess.Popen(['curl', str(emailurl)], stdout=subprocess.PIPE)
            temp = process.communicate()[0]
        else:
            print("Empty string")
            temp =  "please enter valid E-mail Address"


        return render_template("subscribe.html",data=temp)

from app.users.views import users

app.register_blueprint(users, url_prefix="/users")


### API Routes
from app.resources.users import Users, UserLogin, UserByEmail

@jwt.revoked_token_loader
def token_de_acesso_invalidado():
    return jsonify({'message': 'You have been logged out.'}), 401 # unauthorized

api.add_resource(Users, '/api/users')
api.add_resource(UserLogin, '/api/login')
api.add_resource(UserByEmail, '/api/users/email/<string:email>')

app/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from app import db
from flask_login import login_user, current_user, logout_user, login_required


from app.users.model import User

from app.users.forms import RegistrationForm, LoginForm

users = Blueprint('users', __name__)

# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        
        user = User(name=sanitize_input(form.name.data),
                    phone=sanitize_input(form.phone.data),
                    email=sanitize_input(form.email.data),
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/registered', methods=['GET'])
def registered():
    return render_template('registered.html')

# LIST
@users.route('/list')
@login_required
def list():
    # Grab a list of users from database.
    users = User.query.all()
    return render_template('list_users.html', users=users)

@users.route('/<int:user_id>/delete', methods=['GET', 'POST'])
def delete_user(user_id):

    user = User.query.get_or_404(user_id)
    
    db.session.delete(user)
    db.session.commit()
    flash('User Deleted')
    return redirect(url_for('users.list'))

@users.route('/login',methods=['GET','POST'])
def login():
    error = None
    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()
        
        if user is not None and user.check_password(form.password.data) :
            login_user(user)
            flash('Log in Success!')
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('index')
            return redirect(next)
        else: 
            error = 'Invalid credentials'
            print('credetials wrong')

            
    return render_template('login.html', form=form, error=error)

@users.route('/flaw', methods=['GET','POST'])
def hello_xss():
    name = "world"
    template = 'unsafe.html' 
    if request.args.get('name'):
        name = request.args.get('name')
    return render_template(template, name=name)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("index"))

def sanitize_input(raw: str) -> str:
    CLEAR = ""
    return raw.replace("'", CLEAR).replace("--", CLEAR).replace(";", CLEAR).replace("%", CLEAR)

app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Free Bootstrap Theme | webthemez</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="" />
<meta name="author" content="http://webthemez.com" />
<!-- css -->

<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='fancybox/jquery.fancybox.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='jcarousel.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='flexslider.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

 

</head>
<body>
<div id="wrapper">

	<!-- start header -->
		<header>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                  <!-- <a class="navbar-brand" href="index.html"><img src="img/logo.png" alt="logo"/></a> -->
				  <a class="navbar-brand" href="index.html"><img src="{{url_for('static', filename='img/logo1.png')}}" alt="logo"/></a>

                </div>
                <div class="navbar-collapse collapse ">
                    <ul class="nav navbar-nav">
                        <li><a href="index.html">Home</a></li> 
						<li class="active"><a href="#">About Us</a></li>
						<li><a href="#">Services</a></li>
                        <li><a href="#">Portfolio</a></li>
                        <li><a href="#">Pricing</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
	</header><!-- end header -->
	<section id="inner-headline">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="pageTitle">Protecting critical infrastructure in all phases of your application</h2>
			</div>
		</div>
	</div>
	</section>
	<section id="content">
	<div class="container">
					
					<div class="about">
					
						<div class="row"> 
							<div class="col-md-12">
								<div class="about-logo">
									<p>
										As more application teams adopt Continuous Integration/Continuous Delivery (CI/CD) workflows to enable application development, it’s increasingly important that organizations have integrated and automated security in place to protect these workflows.
										</p>
                                    	<p>CI/CD pipelines are at the center of daily operations for businesses across industries. When set up properly, they ensure consistency across delivery processes by automating manual tasks and providing visibility into how software is being worked on. It is within these pipelines where a network’s infrastructure has access to various resources, including code signing credentials and analytics keys. </p>
										<p>Since most modern applications are based on a micro-service architecture, DevOps teams have leveraged containers and container orchestration platforms, such as Kubernetes, to build and deploy their applications. As a result, container security must be a critical component of any solution that tries to protect CI/CD workflows. Below are considerations for DevOps teams to ensure their container strategy isn’t compromising security. </p>
								</div>
							</div>
							
						</div>
						
						<hr>
						<br>
						<div class="row"> 
							<div class="col-md-12">
								<h3>How DevSecOps Teams Can Achieve Security for the Entire Applications Lifecycle</h3>
								<div class="about-logo">
									<p>Security should not be limited to only one part of a DevOps workflow. Instead, it needs to be injected into every stage of a CI/CD workflow pipeline—from the time that a developer checks in code to a code repository, until the time that the application is deployed to a runtime environment. At a high-level, a CI/CD pipeline is comprised of three stages: build, deploy, and run. It is paramount to secure each stage of the pipeline to prevent breaches in the overall lifecycle of an application. Here are five things to keep top of mind during each stage of the CI/CD workflow pipeline:  </p>

								</div>
							</div>
							<div class="col-md-12">

								<img src="{{url_for('static', filename='img/pipeline.png')}}"/>
							</div>
						</div>
						
						<div class="row">
							
							<div class="col-md-4">
								<div class="block-heading-two">
									<h3><span>Our Solution</span></h3>
								</div>		
								<!-- Accordion starts -->
								<div class="panel-group" id="accordion-alt3">
								 <!-- Panel. Use "panel-XXX" class for different colors. Replace "XXX" with color. -->
								  <div class="panel">	
									<!-- Panel heading -->
									 <div class="panel-heading">
										<h4 class="panel-title">
										  <a data-toggle="collapse" data-parent="#accordion-alt3" href="#collapseOne-alt3">
											<i class="fa fa-angle-right"></i> Accordion Heading Text Item # 1
										  </a>
										</h4>
									 </div>
									 <div id="collapseOne-alt3" class="panel-collapse collapse">
										<!-- Panel body -->
										<div class="panel-body">
										  Sed ut perspiciaatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas
										</div>
									 </div>
								  </div>
								  <div class="panel">
									 <div class="panel-heading">
										<h4 class="panel-title">
										  <a data-toggle="collapse" data-parent="#accordion-alt3" href="#collapseTwo-alt3">
											<i class="fa fa-angle-right"></i> Accordion Heading Text Item # 2
										  </a>
										</h4>
									 </div>
									 <div id="collapseTwo-alt3" class="panel-collapse collapse">
										<div class="panel-body">
										  Sed ut perspiciaatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas
										</div>
									 </div>
								  </div>
								  <div class="panel">
									 <div class="panel-heading">
										<h4 class="panel-title">
										  <a data-toggle="collapse" data-parent="#accordion-alt3" href="#collapseThree-alt3">
											<i class="fa fa-angle-right"></i> Accordion Heading Text Item # 3
										  </a>
										</h4>
									 </div>
									 <div id="collapseThree-alt3" class="panel-collapse collapse">
										<div class="panel-body">
										  Sed ut perspiciaatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas
										</div>
									 </div>
								  </div>
								  <div class="panel">
									 <div class="panel-heading">
										<h4 class="panel-title">
										  <a data-toggle="collapse" data-parent="#accordion-alt3" href="#collapseFour-alt3">
											<i class="fa fa-angle-right"></i> Accordion Heading Text Item # 4
										  </a>
										</h4>
									 </div>
									 <div id="collapseFour-alt3" class="panel-collapse collapse">
										<div class="panel-body">
										  Sed ut perspiciaatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas
										</div>
									 </div>
								  </div>
								</div>
								<!-- Accordion ends -->
								
							</div>
							
							
							
						</div>
						
						 						
				
						
						
					</div>
									
				</div>
	</section>
	<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="widget">
					<h4 class="widgetheading">Cloud Consulting</h4>
					
					<p>
						<i class="icon-envelope-alt"></i> consulting@fortinet.com
					</p>
				</div>
			</div>
		
		</div>
	</div>
	
	</footer>
</div>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
<!-- javascript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{url_for('static', filename='js/jquery.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.easing.1.3.js')}}"></script>
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.fancybox.pack.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.fancybox-media.js')}}"></script> 
<script src="{{url_for('static', filename='js/portfolio/jquery.quicksand.js')}}"></script> 
<script src="{{url_for('static', filename='js/portfolio/js/portfolio/setting.js')}}"></script> 
<script src="{{url_for('static', filename='js/jquery.flexslider.js')}}"></script> 
<script src="{{url_for('static', filename='js/animate.js')}}"></script> 
<script src="{{url_for('static', filename='js/custom.js')}}"></script> 

</body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Demo App - KubeCon 2022</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="" />
<meta name="author" content="http://webthemez.com" />
<!-- css -->

<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='fancybox/jquery.fancybox.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='jcarousel.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='flexslider.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

 

</head>
<body>
<div id="wrapper">

	<!-- start header -->
		<header>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                  <!-- <a class="navbar-brand" href="index.html"><img src="img/logo.png" alt="logo"/></a> -->
				  <a class="navbar-brand" href="/"><img src="{{url_for('static', filename='img/logo1.png')}}" alt="logo"/></a>

                </div>
                <div class="navbar-collapse collapse ">
                    <ul class="nav navbar-nav">
                        <li> <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a></li> 
						<li class="nav-item nav-link"><a class="nav-item nav-link" href="/users/register">Register</a></li>
                        <li><a class="nav-item nav-link" href="/subscribe">Subscribe</a></li>
                        {% if current_user.is_authenticated %}
						<li><a class="nav-item nav-link" href="/users/list">List Users</a></li>
                        <li><a class="nav-item nav-link" href="{{ url_for('users.logout')}}">Logout</a></li>
                        {% else %}
                        <li><a class="nav-item nav-link" href="{{ url_for('users.login') }}">Log In</a></li>
                        {% endif %}
                        
                    </ul>
                </div>
            </div>
        </div>
	</header><!-- end header -->
 
   <br>
   <br>
	<section id="">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {% block content %}

        {% endblock %}

                </div>
    
                
            </div>
        </div>

        

    </section>
   


    <br>
	<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="widget">
					<h4 class="widgetheading">Cloud Consulting</h4>
					
					<p>
						<i class="icon-envelope-alt"></i> consulting@fortinet.com
					</p>
				</div>
			</div>
		
		</div>
	</div>
	
	</footer>
</div>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
<!-- javascript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{url_for('static', filename='js/jquery.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.easing.1.3.js')}}"></script>
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.fancybox.pack.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery.fancybox-media.js')}}"></script> 
<script src="{{url_for('static', filename='js/portfolio/jquery.quicksand.js')}}"></script> 
<script src="{{url_for('static', filename='js/portfolio/js/portfolio/setting.js')}}"></script> 
<script src="{{url_for('static', filename='js/jquery.flexslider.js')}}"></script> 
<script src="{{url_for('static', filename='js/animate.js')}}"></script> 
<script src="{{url_for('static', filename='js/custom.js')}}"></script> 

</body>
</html>

app/templates/base_old.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>K8S Demo App - Jenkins</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a>      
      <a class="nav-item nav-link" href="/users/register">Register</a>


      {% if current_user.is_authenticated %}
      <a class="nav-item nav-link" href="/users/list">List Users</a>

      <a class="nav-item nav-link" href="{{ url_for('users.logout')}}">Logout</a>
      {% else %}

      <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Log In</a>
      {% endif %}

    </div>

</nav>

    {% block content %}

    {% endblock %}

    
  </body>
</html>

app/templates/email.html
<html>
    <head>
        <title>
            K8S Demo APP
        </title>
        
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet"><link rel="stylesheet" href="classless.css" />

        <link rel="stylesheet" href="https://classless.de/classless.css">
    </head>
    <body>
        <h2>Welcome</h2>

            <form method="POST" action="/flaw">
    
                <label for="email">Email ID:</label><br>
                <input type="text" id="email" name="email" value=""><br><br>
                <input type="submit" value="Subscribe">
                   
                        {{data}}
                  
    
        
              </form>

  

    </body>

  
</html>

app/templates/list_users.html
{% extends "base.html" %}
{% block content %}

  <div class="container"> 
    <div class="row">
      <div class="col-md-12">
        <div class="page-header">
        <h1>Users Registered</h1>
        </div>
      </div>
      </div>
</div>


<div class="container">
  <div class="row">
    <table class="table">
      <thead>
          <tr>
              <th>ID</th>
              <th>Email</th>
              <th>Name</th>
              <th>Phone</th>
              <th>Registration Date</th>
              <th>Admin</th>
              <th>Change</th>

          <tr>
      </thead>
      <tbody>
          {% for u in users %}
          <tr>
              <td>{{ u.id }}</td>
              <td>{{ u.email }}</td>
              <td>{{ u.name }}</td>
              <td>{{ u.phone }}</td>
              <td>{{ u.date }}</td>
              <td>{{ u.admin }}</td>
              <td> 
                <a class="btn btn-danger" href="{{url_for('users.delete_user', user_id=u.id)}}"> Delete</a>
              
                </td>

              
          </tr>
          {% endfor %}
      </tbody>
  </table>


</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block content %}

<style>
    form {border: 3px solid #f1f1f1;}
    
    input[type=text], input[type=password] {
      width: 100%;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      box-sizing: border-box;
    }
    
    button {
      background-color: #4CAF50;
      color: white;
      padding: 14px 20px;
      margin: 8px 0;
      border: none;
      cursor: pointer;
      width: 100%;
    }
    
    button:hover {
      opacity: 0.8;
    }
    
    .cancelbtn {
      width: auto;
      padding: 10px 18px;
      background-color: #f44336;
    }
    
    .imgcontainer {
      text-align: center;
      margin: 12px 0 6px 0;
    }
    
    img.avatar {
      width: 15%;
      border-radius: 10%;
    }
    
    .container {
      padding: 16px;
    }
    
    span.psw {
      float: right;
      padding-top: 16px;
    }
    
    /* Change styles for span and cancel button on extra small screens */
    @media screen and (max-width: 300px) {
      span.psw {
         display: block;
         float: none;
      }
      .cancelbtn {
         width: 100%;
      }
    }
    </style>
    <div class="container" style="text-align: center; margin-top:2%">
    <h2>Login - Admin</h2>
    </div>
    <div class="col-12">

     
    </div>

    <div class="col-12">

    <form  method="POST">
        {{form.hidden_tag()}}
        <div class="imgcontainer">

        </div>
      
        <div class="container">
          <label for="uname"><b>{{form.email.label()}}</b></label>

          
          {{form.email()}}
      
          <label for="psw"><b>{{form.password.label()}}</b></label>

        {{form.password()}}

        {% if error %}
        <!-- <p class="error" style="text-align: center; color:red"><strong>{{ error }}</strong>  -->



        {% endif %}
              

          {{form.submit(class="btn btn-success btn-block")}}

         
        </div>
      
        
      </form>
     
    </div>





{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block content %}

<style>

    .form-group {
        margin-bottom: 0rem;
    }
</style>

<div class="container">

    <div class="col-md-4">

    </div>
    <div class="col-md-4">

    <form class="form-group" method="POST">
        {{form.hidden_tag()}}

        <div class="form-group">
            {{form.name.label(class="form-control-label ")}}{{form.name(class="form-control form-control-lg")}} <br>
            
        </div>

       
        <div class="form-group">
            {{form.phone.label(class="form-control-label")}}{{form.phone(class="form-control form-control-lg")}} <br>
        </div>

        <div class="form-group">
            {{form.email.label(class="form-control-label")}}{{form.email(class="form-control form-control-lg")}} <br>

        </div>

        <div class="form-group">
            {{form.password.label(class="form-control-label")}}{{form.password(class="form-control form-control-lg")}} <br>

        </div>

        <div class="form-group">
            {{form.pass_confirm.label(class="form-control-label")}}{{form.pass_confirm(class="form-control form-control-lg")}} <br>

        </div>
        

        {{form.submit(class="btn btn-success btn-block")}}

    </form>
</div>
<div class="col-md-4">

</div>
</div>

{% endblock %}

app/templates/registered.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  
    <h6>User registered successfully!</h6>

    <a href="">Log In</a>
    
</div>  
  

{% endblock %}

app/templates/subscribe.html
{% extends "base.html" %}
{% block content %}

<div class="container"> 
    <div class="row">
      <div class="col-md-12">
        <div class="page-header">
        <h1>Subscribe</h1>
        </div>
      </div>
      </div>
</div>

<div class="container"> 
    <div class="row">
      <div class="col-lg-12">
      </div>
      <form method="POST" class="form-group" action="/subscribe">
    
        <label class="form-control-label" for="email" style="width: 60%;">Email ID:</label><br>
        <input type="text" id="email" name="email" style="width: 60%;" value=""><br><br>
        <input type="submit" value="Subscribe" style="width: 60%;">
           
          
      </form>
      <div class="col-lg-12">
        {{data}}


      </div>
    

      </div>
</div>


{% endblock %}

app/templates/unsafe.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">

  <div class="container"> 
    <div class="row">
      <div class="col-md-12">
        <h1>Unsafe Page</h1>
        Hello {{name}}. Becareful!
      </div>
      </div>
</div>
</div>

{% endblock %}